# SITE CONFIGURATION
title: Salvador Aleguas | Portfolio # your site title
author: saleguas # You :P
description: > # Meta description of Homepage
    The developer portfolio of open source developer & software engineer Salvador Aleguas.
baseurl: "/test-website" # the subpath of your site, e.g. /blog
url: "https://saleguas.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Salvador Aleguas
  links:
    - https://www.linkedin.com/in/saleguas
    - https://github.com/saleguas
    - https://medium.com/@salvadoraleguas

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Blog', link: '/blog'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}


tagline: >
  The Portfolio portfolio for Salvador Aleguas

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: salvadoraleguas@gmail.com # email for form submission

github_username:  saleguas # replace with your_github_username or comment to remove link from footer

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
